name: Bug Report
description: Report an issue with Anya
title: "AIT-XXX: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue with Anya!
        Please fill out this form as completely as possible.

  - type: input
    id: ait-number
    attributes:
      label: AIT Number
      description: The assigned Anya Issue Tracking number
      placeholder: "AIT-XXX"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Issue Severity
      description: How severe is this issue?
      options:
        - Critical - System unusable
        - High - Major functionality impacted
        - Medium - Partial functionality impacted
        - Low - Minor inconvenience
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you're encountering
      placeholder: |
        A clear and concise description of what the bug is.
        Include any error messages or unexpected behavior.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g. Windows 10]
        - Browser: [e.g. Chrome 91]
        - Anya Version: [e.g. 1.3.0]
    validations:
      required: true

  - type: textarea
    id: ai-context
    attributes:
      label: AI Context
      description: Describe any AI-specific context relevant to this issue
      placeholder: |
        - Were you using specific AI features?
        - Any patterns in AI behavior?
        - Related AI improvements or patterns?
    validations:
      required: false

  - type: textarea
    id: related-items
    attributes:
      label: Related Items
      description: List any related AI-labeled items
      placeholder: |
        - AIR-001: Related improvement request
        - AIS-002: Related specification
        - AIP-003: Related pattern
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow Anya's Code of Conduct
          required: true
